Ext.define('Tnewone.tnewone.shared.com.model.appinsight.health.AAAAAuiModel', {
     "extend": "Ext.data.Model",
     "fields": [{
          "name": "t1",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "t2",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "t3",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "t4",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "t5",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "b1",
          "type": "auto",
          "defaultValue": ""
     }, {
          "name": "b2",
          "type": "auto",
          "defaultValue": ""
     }]
});