Ext.define('Tnewone.tnewone.shared.com.model.newreportbc.newreport.ToneUiModel', {
     "extend": "Ext.data.Model",
     "fields": [{
          "name": "t1",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "t2",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "t3",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "tt4",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "t5",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "t6",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "t7",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "t8",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "t9",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "t10",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "t11",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "b1",
          "type": "auto",
          "defaultValue": ""
     }, {
          "name": "b2",
          "type": "auto",
          "defaultValue": ""
     }, {
          "name": "b3",
          "type": "auto",
          "defaultValue": ""
     }, {
          "name": "b4",
          "type": "auto",
          "defaultValue": ""
     }, {
          "name": "b5",
          "type": "auto",
          "defaultValue": ""
     }]
});