Ext.define('Testtwo.testtwo.shared.com.model.appinsight.health.SSSSSModel', {
     "extend": "Ext.data.Model",
     "fields": [{
          "name": "t1",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "c1",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "t2",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "t3",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "t4",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "t5",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "b1",
          "type": "auto",
          "defaultValue": ""
     }, {
          "name": "b2",
          "type": "auto",
          "defaultValue": ""
     }, {
          "name": "b3",
          "type": "auto",
          "defaultValue": ""
     }, {
          "name": "b4",
          "type": "auto",
          "defaultValue": ""
     }, {
          "name": "b5",
          "type": "auto",
          "defaultValue": ""
     }, {
          "name": "b6",
          "type": "auto",
          "defaultValue": ""
     }, {
          "name": "b7",
          "type": "auto",
          "defaultValue": ""
     }, {
          "name": "b8",
          "type": "auto",
          "defaultValue": ""
     }, {
          "name": "b9",
          "type": "auto",
          "defaultValue": ""
     }, {
          "name": "c2",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "c3",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "c4",
          "type": "string",
          "defaultValue": ""
     }]
});