DROP TABLE IF EXISTS `ast_TestThree_T`;

CREATE TABLE `ast_TestThree_T` ( `tttid` VARCHAR(256) NOT NULL, `ttnm` VARCHAR(256) NOT NULL, `nnno` VARCHAR(256) NOT NULL, `gen` VARCHAR(64) NOT NULL, `addd` VARCHAR(64) NOT NULL, `createdBy` VARCHAR(64) NULL DEFAULT '-1', `createdDate` TIMESTAMP NULL DEFAULT '2000-01-01 10:10:10', `updatedBy` VARCHAR(64) NULL DEFAULT '-1', `updatedDate` TIMESTAMP NULL DEFAULT '2000-01-01 10:10:10', `versionId` INT(11) NULL DEFAULT '-1', `activeStatus` INT(1) NULL DEFAULT '1', `txnAccessCode` INT(11) NULL DEFAULT NULL, PRIMARY KEY (`tttid`));

