DROP TABLE IF EXISTS `ast_TestOne_M`;

CREATE TABLE `ast_TestOne_M` ( `tid` VARCHAR(256) NOT NULL, `tnm` VARCHAR(256) NOT NULL, `tno` INT(10) NOT NULL, `gen` VARCHAR(64) NOT NULL, `addqadd` VARCHAR(64) NOT NULL, `createdBy` VARCHAR(64) NULL DEFAULT '-1', `createdDate` TIMESTAMP NULL DEFAULT '2000-01-01 10:10:10', `updatedBy` VARCHAR(64) NULL DEFAULT '-1', `updatedDate` TIMESTAMP NULL DEFAULT '2000-01-01 10:10:10', `versionId` INT(11) NULL DEFAULT '-1', `activeStatus` INT(1) NULL DEFAULT '1', `txnAccessCode` INT(11) NULL DEFAULT NULL, PRIMARY KEY (`tid`));

