DROP TABLE IF EXISTS `ast_Child_TP`;

CREATE TABLE `ast_Child_TP` ( `pid` VARCHAR(256) NOT NULL, `cid` VARCHAR(256) NOT NULL, `cName` VARCHAR(256) NOT NULL, `cage` INT(10) NOT NULL, `addr` VARCHAR(64) NOT NULL, `createdBy` VARCHAR(64) NULL DEFAULT '-1', `createdDate` TIMESTAMP NULL DEFAULT '2000-01-01 10:10:10', `updatedBy` VARCHAR(64) NULL DEFAULT '-1', `updatedDate` TIMESTAMP NULL DEFAULT '2000-01-01 10:10:10', `versionId` INT(11) NULL DEFAULT '-1', `activeStatus` INT(1) NULL DEFAULT '1', `txnAccessCode` INT(11) NULL DEFAULT NULL, PRIMARY KEY (`cid`));

