DROP TABLE IF EXISTS `ast_Stwo_M`;

CREATE TABLE `ast_Stwo_M` ( `stwoid` VARCHAR(256) NOT NULL, `snmn` VARCHAR(256) NOT NULL, `sds` VARCHAR(64) NOT NULL, `createdBy` VARCHAR(64) NULL DEFAULT '-1', `createdDate` TIMESTAMP NULL DEFAULT '2000-01-01 10:10:10', `updatedBy` VARCHAR(64) NULL DEFAULT '-1', `updatedDate` TIMESTAMP NULL DEFAULT '2000-01-01 10:10:10', `versionId` INT(11) NULL DEFAULT '-1', `activeStatus` INT(1) NULL DEFAULT '1', `txnAccessCode` INT(11) NULL DEFAULT NULL, PRIMARY KEY (`stwoid`));

