Ext.define('Tnewone.tnewone.web.com.view.newreportbc.newreport.ToneUi', {
     "xtype": "toneUi",
     "items": [{
          "xtype": "textfield",
          "fieldLabel": "TextField",
          "margin": 5,
          "bindable": "t1",
          "name": "t1",
          "itemId": "textfield_ext_13061"
     }, {
          "xtype": "textfield",
          "fieldLabel": "TextField",
          "margin": 5,
          "bindable": "t2",
          "name": "t2",
          "itemId": "textfield_ext_13071"
     }, {
          "xtype": "textfield",
          "fieldLabel": "TextField",
          "margin": 5,
          "bindable": "t3",
          "name": "t3",
          "itemId": "textfield_ext_13084"
     }, {
          "xtype": "textfield",
          "fieldLabel": "TextField",
          "margin": 5,
          "bindable": "tt4",
          "name": "tt4",
          "itemId": "textfield_ext_13098"
     }, {
          "xtype": "textfield",
          "fieldLabel": "TextField",
          "margin": 5,
          "bindable": "t5",
          "name": "t5",
          "itemId": "textfield_ext_13114"
     }, {
          "xtype": "textfield",
          "fieldLabel": "TextField",
          "margin": 5,
          "bindable": "t6",
          "name": "t6",
          "itemId": "textfield_ext_13132"
     }, {
          "xtype": "textfield",
          "fieldLabel": "TextField",
          "margin": 5,
          "bindable": "t7",
          "name": "t7",
          "itemId": "textfield_ext_13152"
     }, {
          "xtype": "textfield",
          "fieldLabel": "TextField",
          "margin": 5,
          "bindable": "t8",
          "name": "t8",
          "itemId": "textfield_ext_13174"
     }, {
          "xtype": "textfield",
          "fieldLabel": "TextField",
          "margin": 5,
          "bindable": "t9",
          "name": "t9",
          "itemId": "textfield_ext_13199"
     }, {
          "xtype": "textfield",
          "fieldLabel": "TextField",
          "margin": 5,
          "bindable": "t10",
          "name": "t10",
          "itemId": "textfield_ext_13225"
     }, {
          "xtype": "textfield",
          "fieldLabel": "TextField",
          "margin": 5,
          "bindable": "t11",
          "name": "t11",
          "itemId": "textfield_ext_13253"
     }, {
          "xtype": "button",
          "name": "b1",
          "text": "Button",
          "margin": 5,
          "itemId": "button_ext_13283",
          "listeners": {
               "click": "onB1Click"
          }
     }, {
          "xtype": "button",
          "name": "b2",
          "text": "Button",
          "margin": 5,
          "itemId": "button_ext_13315",
          "listeners": {
               "click": "onB2Click"
          }
     }, {
          "xtype": "button",
          "name": "b3",
          "text": "Button",
          "margin": 5,
          "itemId": "button_ext_13349",
          "listeners": {
               "click": "onB3Click"
          }
     }, {
          "xtype": "button",
          "name": "b4",
          "text": "Button",
          "margin": 5,
          "itemId": "button_ext_13385",
          "listeners": {
               "click": "onB4Click"
          }
     }, {
          "xtype": "button",
          "name": "b5",
          "text": "Button",
          "margin": 5,
          "itemId": "button_ext_13423",
          "listeners": {
               "click": "onB5Click"
          }
     }],
     "border": true,
     "autoScroll": true,
     "title": "Form",
     "margin": 5,
     "itemId": "form_ext_13052",
     "dockedItems": [],
     "extend": "Ext.form.Panel",
     "requires": ["Tnewone.tnewone.web.com.controller.newreportbc.newreport.ToneUiController", "Tnewone.tnewone.shared.com.viewmodel.newreportbc.newreport.ToneUiViewModel", "Tnewone.tnewone.shared.com.model.newreportbc.newreport.ToneUiModel"],
     "viewModel": "ToneUiViewModel",
     "controller": "ToneUiController"
});