Ext.define('Testpro.testpro.shared.com.model.appinsight.health.AtwoModel', {
     "extend": "Ext.data.Model",
     "fields": [{
          "name": "primaryKey",
          "type": "auto",
          "defaultValue": ""
     }, {
          "name": "aaid",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "gfg",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "gen",
          "reference": "Gender",
          "defaultValue": ""
     }, {
          "name": "versionId",
          "type": "int",
          "defaultValue": ""
     }, {
          "name": "entityAudit",
          "reference": "EntityAudit"
     }, {
          "name": "primaryDisplay",
          "type": "string",
          "defaultValue": ""
     }]
});